.only-default: &only-default
  only:
    - merge_requests

.only-default-mr: &only-default-mr
  only:
    - merge_requests
    - master

include:
  - project: 'infrastructure/ci-helm'
    ref: master
    file: 'ci-templates/ci.yml'

variables:
  PRODUCT: dap
  MICROSERVICE_NAME: dap_etlp_mapper
  DOCKER_IMAGE: data-standardization/etlp-mapper
  BUILD_TYPE: DOCKERCOMPOSE
  DELAY: "11 min"
  CI_SONAR_COVERAGE_REPORT_PATH: "target/coverage/coverage.xml"

StyleCheck:
  image: clojure:lein
  stage: linting
  variables:
   KUBERNETES_SERVICE_MEMORY_LIMIT: 4Gi
   KUBERNETES_SERVICE_CPU_LIMIT: 4
  script:
    - echo "TODO lint"
  tags:
    - docker
  allow_failure: false
  <<: *only-default

.Coverage:
  image: clojure:lein
  tags:
    - gitlab-runner
  allow_failure: false
  <<: *only-default

MasterCoverage:
  stage: test
  script:
    - echo "SKIP master coverage check"
  tags:
    - docker
  <<: *only-default

Coverage-Check:
  stage: coverage-check
  script:
    - echo "SKIP coverage check"
  tags:
    - docker
  <<: *only-default
